/** This program can be used by companies and organizations to generate email accounts for employees.
 The Email class (using an inputted name) can be used to create the email, set the department,
 set the password, set mailbox capacity, create an alternate email, and change the password.
 The main method is used to create a new email object, and print the information generated by
 the email class.
 @georgiaheadley
 */
public class EmailApp {

    public static void main(String[] args) {
        // create new email object with input name John Smith
        Email em1 = new Email("John", "Smith");

        // prints the information generated in the Email class
        System.out.println(em1.showInfo());
    }
}
